# Generated by Django 3.2.7 on 2021-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('birth_date', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=2)),
                ('job', models.CharField(max_length=30)),
                ('added_date', models.CharField(max_length=30)),
                ('added_by', models.CharField(max_length=30)),
            ],
        ),
    ]
