# Generated by Django 3.2.7 on 2021-09-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
