# Generated by Django 3.2.7 on 2021-10-01 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 12, 50, 33, 295486, tzinfo=utc)),
        ),
    ]
