# Generated by Django 3.2.7 on 2021-10-02 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_person_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='added_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 2, 8, 51, 14, 900479, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
